pool:
  vmImage: 'windows-latest'

trigger: none
pr: none

resources:
  pipelines:
  - pipeline: DnDGen.CharacterGen
    source: 'DnDGen.CharacterGen - Build'
    trigger: 
      branches:
      - master

jobs:

- deployment: CharacterGen_Nuget
  displayName: Deploy CharacterGen NuGet Package
  environment: Prod
  strategy:
    runOnce:
      deploy:
        steps:
        - task: NuGetCommand@2
          displayName: 'NuGet push'
          inputs:
            command: push
            packagesToPush: '$(Pipeline.Workspace)/**/DnDGen.CharacterGen.*.nupkg'
            nuGetFeedType: external
            publishFeedCredentials: NuGet.org
        - task: GitHubRelease@1
          displayName: 'GitHub release (create)'
          inputs:
            gitHubConnection: 'github.com_cidthecoatrack'
            assets: '$(Pipeline.Workspace)/**/DnDGen.CharacterGen.*.nupkg'
