using System;
using NPCGen.Common.Abilities.Feats;
using NUnit.Framework;

namespace NPCGen.Tests.Unit.Common.Abilities.Feats
{
    [TestFixture]
    public class FeatConstantsTests
    {
        [TestCase(FeatConstants.AasimarDaylight, "Aasimar Special Attack: Daylight")]
        [TestCase(FeatConstants.AasimarDaylightId, "AasimarDaylight")]
        [TestCase(FeatConstants.Ambidexterity, "Ambidexterity")]
        [TestCase(FeatConstants.AmbidexterityId, "Ambidexterity")]
        [TestCase(FeatConstants.Darkvision, "Darkvision")]
        [TestCase(FeatConstants.DarkvisionId, "Darkvision")]
        [TestCase(FeatConstants.LightArmorProficiency, "Light Armor Proficiency")]
        [TestCase(FeatConstants.LightArmorProficiencyId, "LightArmorProficiency")]
        [TestCase(FeatConstants.ResistanceToAcid, "Resistance to Acid")]
        [TestCase(FeatConstants.ResistanceToAcidId, "ResistanceToAcid")]
        [TestCase(FeatConstants.ResistanceToCold, "Resistance to Cold")]
        [TestCase(FeatConstants.ResistanceToColdId, "ResistanceToCold")]
        [TestCase(FeatConstants.ResistanceToElectricity, "Resistance to Electricity")]
        [TestCase(FeatConstants.ResistanceToElectricityId, "ResistanceToElectricity")]
        [TestCase(FeatConstants.Scent, "Scent")]
        [TestCase(FeatConstants.ScentId, "Scent")]
        [TestCase(FeatConstants.ShieldProficiency, "Shield Proficiency")]
        [TestCase(FeatConstants.ShieldProficiencyId, "ShieldProficiency")]
        [TestCase(FeatConstants.SkillFocus, "Skill Focus")]
        [TestCase(FeatConstants.SkillFocusId, "SkillFocus")]
        [TestCase(FeatConstants.SpellMastery, "Spell Mastery")]
        [TestCase(FeatConstants.SpellMasteryId, "SpellMastery")]
        [TestCase(FeatConstants.Stability, "Stability")]
        [TestCase(FeatConstants.StabilityId, "Stability")]
        [TestCase(FeatConstants.Stonecunning, "Stonecunning")]
        [TestCase(FeatConstants.StonecunningId, "Stonecunning")]
        [TestCase(FeatConstants.WeaponFamiliarity, "Weapon Familiarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.Acrobatic, "Acrobatic")]
        [TestCase(FeatConstants.AcrobaticId, "Acrobatic")]
        [TestCase(FeatConstants.Agile, "Agile")]
        [TestCase(FeatConstants.AgileId, "Agile")]
        [TestCase(FeatConstants.Alertness, "Alertness")]
        [TestCase(FeatConstants.AlertnessId, "Alertness")]
        [TestCase(FeatConstants.AnimalAffinity, "Animal Affinity")]
        [TestCase(FeatConstants.AnimalAffinityId, "AnimalAffinity")]
        [TestCase(FeatConstants.MediumArmorProficiency, "Medium Armor Proficiency")]
        [TestCase(FeatConstants.MediumArmorProficiencyId, "MediumArmorProficiency")]
        [TestCase(FeatConstants.HeavyArmorProficiency, "Heavy Armor Proficiency")]
        [TestCase(FeatConstants.HeavyArmorProficiencyId, "HeavyArmorProficiency")]
        [TestCase(FeatConstants.Athletic, "Athletic")]
        [TestCase(FeatConstants.AthleticId, "Athletic")]
        [TestCase(FeatConstants.AugmentSummoning, "Augment Summoning")]
        [TestCase(FeatConstants.AugmentSummoningId, "AugmentSummoning")]
        [TestCase(FeatConstants.BlindFight, "Blind-Fight")]
        [TestCase(FeatConstants.BlindFightId, "BlindFight")]
        [TestCase(FeatConstants.CombatCasting, "Combat Casting")]
        [TestCase(FeatConstants.CombatCastingId, "CombatCasting")]
        [TestCase(FeatConstants.CombatExpertise, "Combat Expertise")]
        [TestCase(FeatConstants.CombatExpertiseId, "CombatExpertise")]
        [TestCase(FeatConstants.ImprovedDisarm, "Improved Disarm")]
        [TestCase(FeatConstants.ImprovedDisarmId, "ImprovedDisarm")]
        [TestCase(FeatConstants.ImprovedFeint, "Improved Feint")]
        [TestCase(FeatConstants.ImprovedFeintId, "ImprovedFeint")]
        [TestCase(FeatConstants.ImprovedTrip, "Improved Trip")]
        [TestCase(FeatConstants.ImprovedTripId, "ImprovedTrip")]
        [TestCase(FeatConstants.WhirlwindAttack, "Whirlwind Attack")]
        [TestCase(FeatConstants.WhirlwindAttackId, "WhirlwindAttack")]
        [TestCase(FeatConstants.CombatReflexes, "Combat Reflexes")]
        [TestCase(FeatConstants.CombatReflexesId, "CombatReflexes")]
        [TestCase(FeatConstants.Deceitful, "Deceitful")]
        [TestCase(FeatConstants.DeceitfulId, "Deceitful")]
        [TestCase(FeatConstants.DeftHands, "Deft Hands")]
        [TestCase(FeatConstants.DeftHandsId, "DeftHands")]
        [TestCase(FeatConstants.Diligent, "Diligent")]
        [TestCase(FeatConstants.DiligentId, "Diligent")]
        [TestCase(FeatConstants.Dodge, "Dodge")]
        [TestCase(FeatConstants.DodgeId, "Dodge")]
        [TestCase(FeatConstants.Mobility, "Mobility")]
        [TestCase(FeatConstants.MobilityId, "Mobility")]
        [TestCase(FeatConstants.SpringAttack, "Spring Attack")]
        [TestCase(FeatConstants.SpringAttackId, "SpringAttack")]
        [TestCase(FeatConstants.Endurance, "Endurance")]
        [TestCase(FeatConstants.EnduranceId, "Endurance")]
        [TestCase(FeatConstants.Diehard, "Diehard")]
        [TestCase(FeatConstants.DiehardId, "Diehard")]
        [TestCase(FeatConstants.EschewMaterials, "Eschew Materials")]
        [TestCase(FeatConstants.EschewMaterialsId, "EschewMaterials")]
        [TestCase(FeatConstants.ExoticWeaponProficiency, "Exotic Weapon Proficiency")]
        [TestCase(FeatConstants.ExoticWeaponProficiencyId, "ExoticWeaponProficiency")]
        [TestCase(FeatConstants.ExtraTurning, "Extra Turning")]
        [TestCase(FeatConstants.ExtraTurningId, "ExtraTurning")]
        [TestCase(FeatConstants.GreatFortitude, "Great Fortitude")]
        [TestCase(FeatConstants.GreatFortitudeId, "GreatFortitude")]
        [TestCase(FeatConstants.ImprovedCounterspell, "Improved Counterspell")]
        [TestCase(FeatConstants.ImprovedCounterspellId, "ImprovedCounterspell")]
        [TestCase(FeatConstants.ImprovedCritical, "Improved Critical")]
        [TestCase(FeatConstants.ImprovedCriticalId, "ImprovedCritical")]
        [TestCase(FeatConstants.ImprovedFamiliar, "Improved Familiar")]
        [TestCase(FeatConstants.ImprovedFamiliarId, "ImprovedFamiliar")]
        [TestCase(FeatConstants.ImprovedInitiative, "Improved Initiative")]
        [TestCase(FeatConstants.ImprovedInitiativeId, "ImprovedInitiative")]
        [TestCase(FeatConstants.ImprovedTurning, "Improved Turning")]
        [TestCase(FeatConstants.ImprovedTurningId, "ImprovedTurning")]
        [TestCase(FeatConstants.ImprovedUnarmedStrike, "Improved Unarmed Strike")]
        [TestCase(FeatConstants.ImprovedUnarmedStrikeId, "ImprovedUnarmedStrike")]
        [TestCase(FeatConstants.DeflectArrows, "Deflect Arrows")]
        [TestCase(FeatConstants.DeflectArrowsId, "DeflectArrows")]
        [TestCase(FeatConstants.ImprovedGrapple, "Improved Grapple")]
        [TestCase(FeatConstants.ImprovedGrappleId, "ImprovedGrapple")]
        [TestCase(FeatConstants.SnatchArrows, "Snatch Arrows")]
        [TestCase(FeatConstants.SnatchArrowsId, "SnatchArrows")]
        [TestCase(FeatConstants.StunningFist, "Stunning Fist")]
        [TestCase(FeatConstants.StunningFistId, "StunningFist")]
        [TestCase(FeatConstants.Investigator, "Investigator")]
        [TestCase(FeatConstants.InvestigatorId, "Investigator")]
        [TestCase(FeatConstants.IronWill, "Iron Will")]
        [TestCase(FeatConstants.IronWillId, "IronWill")]
        [TestCase(FeatConstants.Leadership, "Leadership")]
        [TestCase(FeatConstants.LeadershipId, "Leadership")]
        [TestCase(FeatConstants.LightningReflexes, "Lightning Reflexes")]
        [TestCase(FeatConstants.LightningReflexesId, "LightningReflexes")]
        [TestCase(FeatConstants.MagicalAptitude, "Magical Aptitude")]
        [TestCase(FeatConstants.MagicalAptitudeId, "MagicalAptitude")]
        [TestCase(FeatConstants.MartialWeaponProficiency, "Martial Weapon Proficiency")]
        [TestCase(FeatConstants.MartialWeaponProficiencyId, "MartialWeaponProficiency")]
        [TestCase(FeatConstants.MountedCombat, "Mounted Combat")]
        [TestCase(FeatConstants.MountedCombatId, "MountedCombat")]
        [TestCase(FeatConstants.MountedArchery, "Mounted Archery")]
        [TestCase(FeatConstants.MountedArcheryId, "MountedArchery")]
        [TestCase(FeatConstants.RideByAttack, "Ride-By Attack")]
        [TestCase(FeatConstants.RideByAttackId, "RideByAttack")]
        [TestCase(FeatConstants.SpiritedCharge, "Spirited Charge")]
        [TestCase(FeatConstants.SpiritedChargeId, "SpiritedCharge")]
        [TestCase(FeatConstants.Trample, "Trample")]
        [TestCase(FeatConstants.TrampleId, "Trample")]
        [TestCase(FeatConstants.NaturalSpell, "Natural Spell")]
        [TestCase(FeatConstants.NaturalSpellId, "NaturalSpell")]
        [TestCase(FeatConstants.Negotiator, "Negotiator")]
        [TestCase(FeatConstants.NegotiatorId, "Negotiator")]
        [TestCase(FeatConstants.NimbleFingers, "Nimble Fingers")]
        [TestCase(FeatConstants.NimbleFingersId, "NimbleFingers")]
        [TestCase(FeatConstants.Persuasive, "Persuasive")]
        [TestCase(FeatConstants.PersuasiveId, "Persuasive")]
        [TestCase(FeatConstants.PointBlankShot, "Point Blank Shot")]
        [TestCase(FeatConstants.PointBlankShotId, "PointBlankShot")]
        [TestCase(FeatConstants.FarShot, "Far Shot")]
        [TestCase(FeatConstants.FarShotId, "FarShot")]
        [TestCase(FeatConstants.PreciseShot, "Precise Shot")]
        [TestCase(FeatConstants.PreciseShotId, "PreciseShot")]
        [TestCase(FeatConstants.ImprovedPreciseShot, "Improved Precise Shot")]
        [TestCase(FeatConstants.ImprovedPreciseShotId, "ImprovedPreciseShot")]
        [TestCase(FeatConstants.RapidShot, "Rapid Shot")]
        [TestCase(FeatConstants.RapidShotId, "RapidShot")]
        [TestCase(FeatConstants.Manyshot, "Manyshot")]
        [TestCase(FeatConstants.ManyshotId, "Manyshot")]
        [TestCase(FeatConstants.ShotOnTheRun, "Shot On The Run")]
        [TestCase(FeatConstants.ShotOnTheRunId, "ShotOnTheRun")]
        [TestCase(FeatConstants.PowerAttack, "Power Attack")]
        [TestCase(FeatConstants.PowerAttackId, "PowerAttack")]
        [TestCase(FeatConstants.Cleave, "Cleave")]
        [TestCase(FeatConstants.CleaveId, "Cleave")]
        [TestCase(FeatConstants.GreatCleave, "Great Cleave")]
        [TestCase(FeatConstants.GreatCleaveId, "GreatCleave")]
        [TestCase(FeatConstants.ImprovedBullRush, "Improved Bull Rush")]
        [TestCase(FeatConstants.ImprovedBullRushId, "ImprovedBullRush")]
        [TestCase(FeatConstants.ImprovedOverrun, "Improved Overrun")]
        [TestCase(FeatConstants.ImprovedOverrunId, "ImprovedOverrun")]
        [TestCase(FeatConstants.ImprovedSunder, "Improved Sunder")]
        [TestCase(FeatConstants.ImprovedSunderId, "ImprovedSunder")]
        [TestCase(FeatConstants.QuickDraw, "Quick Draw")]
        [TestCase(FeatConstants.QuickDrawId, "QuickDraw")]
        [TestCase(FeatConstants.RapidReload, "Rapid Reload")]
        [TestCase(FeatConstants.RapidReloadId, "RapidReload")]
        [TestCase(FeatConstants.Run, "Run")]
        [TestCase(FeatConstants.RunId, "Run")]
        [TestCase(FeatConstants.SelfSufficient, "Self-Sufficient")]
        [TestCase(FeatConstants.SelfSufficientId, "SelfSufficient")]
        [TestCase(FeatConstants.ImprovedShieldBash, "Improved Shield Bash")]
        [TestCase(FeatConstants.ImprovedShieldBashId, "ImprovedShieldBash")]
        [TestCase(FeatConstants.TowerShieldProficiency, "Tower Shield Proficiency")]
        [TestCase(FeatConstants.TowerShieldProficiencyId, "TowerShieldProficiency")]
        [TestCase(FeatConstants.SimpleWeaponProficiency, "Simple Weapon Proficiency")]
        [TestCase(FeatConstants.SimpleWeaponProficiencyId, "SimpleWeaponProficiency")]
        [TestCase(FeatConstants.SpellFocus, "Spell Focus")]
        [TestCase(FeatConstants.SpellFocusId, "SpellFocus")]
        [TestCase(FeatConstants.GreaterSpellFocus, "WeaponFamiliarity")]
        [TestCase(FeatConstants.GreaterSpellFocusId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.SpellPenetration, "WeaponFamiliarity")]
        [TestCase(FeatConstants.SpellPenetrationId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.GreaterSpellPenetration, "WeaponFamiliarity")]
        [TestCase(FeatConstants.GreaterSpellPenetrationId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.Stealthy, "Stealthy")]
        [TestCase(FeatConstants.StealthyId, "Stealthy")]
        [TestCase(FeatConstants.Toughness, "Toughness")]
        [TestCase(FeatConstants.ToughnessId, "Toughness")]
        [TestCase(FeatConstants.Track, "Track")]
        [TestCase(FeatConstants.TrackId, "Track")]
        [TestCase(FeatConstants.TwoWeaponFighting, "Two-Weapon Fighting")]
        [TestCase(FeatConstants.TwoWeaponFightingId, "TwoWeaponFighting")]
        [TestCase(FeatConstants.TwoWeaponDefense, "Two-Weapon Defense")]
        [TestCase(FeatConstants.TwoWeaponDefenseId, "TwoWeaponDefense")]
        [TestCase(FeatConstants.ImprovedTwoWeaponFighting, "Improved Two-Weapon Fighting")]
        [TestCase(FeatConstants.ImprovedTwoWeaponFightingId, "ImprovedTwoWeaponFighting")]
        [TestCase(FeatConstants.GreaterTwoWeaponFighting, "Greater Two-Weapon Fighting")]
        [TestCase(FeatConstants.GreaterTwoWeaponFightingId, "GreaterTwoWeaponFighting")]
        [TestCase(FeatConstants.WeaponFinesse, "Weapon Finesse")]
        [TestCase(FeatConstants.WeaponFinesseId, "WeaponFinesse")]
        [TestCase(FeatConstants.WeaponFocus, "Weapon Focus")]
        [TestCase(FeatConstants.WeaponFocusId, "WeaponFocus")]
        [TestCase(FeatConstants.WeaponSpecialization, "Weapon Specialization")]
        [TestCase(FeatConstants.WeaponSpecializationId, "WeaponSpecialization")]
        [TestCase(FeatConstants.GreaterWeaponFocus, "Greater Weapon Focus")]
        [TestCase(FeatConstants.GreaterWeaponFocusId, "GreaterWeaponFocus")]
        [TestCase(FeatConstants.GreaterWeaponSpecialization, "Greater Weapon Specialization")]
        [TestCase(FeatConstants.GreaterWeaponSpecializationId, "GreaterWeaponSpecialization")]
        [TestCase(FeatConstants.EmpowerSpell, "Empower Spell")]
        [TestCase(FeatConstants.EmpowerSpellId, "EmpowerSpell")]
        [TestCase(FeatConstants.EnlargeSpell, "Enlarge Spell")]
        [TestCase(FeatConstants.EnlargeSpellId, "EnlargeSpell")]
        [TestCase(FeatConstants.ExtendSpell, "Extend Spell")]
        [TestCase(FeatConstants.ExtendSpellId, "ExtendSpell")]
        [TestCase(FeatConstants.HeightenSpell, "Heighten Spell")]
        [TestCase(FeatConstants.HeightenSpellId, "HeightenSpell")]
        [TestCase(FeatConstants.MaximizeSpell, "Maximize Spell")]
        [TestCase(FeatConstants.MaximizeSpellId, "MaximizeSpell")]
        [TestCase(FeatConstants.QuickenSpell, "Quicken Spell")]
        [TestCase(FeatConstants.QuickenSpellId, "QuickenSpell")]
        [TestCase(FeatConstants.SilentSpell, "Silent Spell")]
        [TestCase(FeatConstants.SilentSpellId, "SilentSpell")]
        [TestCase(FeatConstants.StillSpell, "Still Spell")]
        [TestCase(FeatConstants.StillSpellId, "StillSpell")]
        [TestCase(FeatConstants.WidenSpell, "Widen Spell")]
        [TestCase(FeatConstants.WidenSpellId, "WidenSpell")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        public void Constant(String constant, String value)
        {
            Assert.That(constant, Is.EqualTo(value));
        }
    }
}