using System;
using NPCGen.Common.Abilities.Feats;
using NUnit.Framework;

namespace NPCGen.Tests.Unit.Common.Abilities.Feats
{
    [TestFixture]
    public class FeatConstantsTests
    {
        [TestCase(FeatConstants.Acrobatic, "Acrobatic")]
        [TestCase(FeatConstants.Agile, "Agile")]
        [TestCase(FeatConstants.Alertness, "Alertness")]
        [TestCase(FeatConstants.AlternateForm, "Alternate Form")]
        [TestCase(FeatConstants.AnimalAffinity, "Animal Affinity")]
        [TestCase(FeatConstants.Athletic, "Athletic")]
        [TestCase(FeatConstants.AttackBonus, "Attack Bonus")]
        [TestCase(FeatConstants.AugmentSummoning, "Augment Summoning")]
        [TestCase(FeatConstants.BlindFight, "Blind-Fight")]
        [TestCase(FeatConstants.ChangeShape, "Change Shape")]
        [TestCase(FeatConstants.Cleave, "Cleave")]
        [TestCase(FeatConstants.CombatCasting, "Combat Casting")]
        [TestCase(FeatConstants.CombatExpertise, "Combat Expertise")]
        [TestCase(FeatConstants.CombatReflexes, "Combat Reflexes")]
        [TestCase(FeatConstants.CripplingStrike, "Crippling Strike")]
        [TestCase(FeatConstants.DamageReduction, "Damage Reduction")]
        [TestCase(FeatConstants.Darkvision, "Darkvision")]
        [TestCase(FeatConstants.Deceitful, "Deceitful")]
        [TestCase(FeatConstants.DefensiveRoll, "Defensive Roll")]
        [TestCase(FeatConstants.DeflectArrows, "Deflect Arrows")]
        [TestCase(FeatConstants.DeftHands, "Deft Hands")]
        [TestCase(FeatConstants.Diehard, "Diehard")]
        [TestCase(FeatConstants.Diligent, "Diligent")]
        [TestCase(FeatConstants.Dodge, "Dodge")]
        [TestCase(FeatConstants.DodgeBonus, "Dodge Bonus")]
        [TestCase(FeatConstants.ElvenBlood, "Elven Blood")]
        [TestCase(FeatConstants.Empathy, "Empathy")]
        [TestCase(FeatConstants.EmpowerSpell, "Empower Spell")]
        [TestCase(FeatConstants.Endurance, "Endurance")]
        [TestCase(FeatConstants.EnlargeSpell, "Enlarge Spell")]
        [TestCase(FeatConstants.EschewMaterials, "Eschew Materials")]
        [TestCase(FeatConstants.Evasion, "Evasion")]
        [TestCase(FeatConstants.ExoticWeaponProficiency, "Exotic Weapon Proficiency")]
        [TestCase(FeatConstants.ExtendSpell, "Extend Spell")]
        [TestCase(FeatConstants.ExtraTurning, "Extra Turning")]
        [TestCase(FeatConstants.FarShot, "Far Shot")]
        [TestCase(FeatConstants.Ferocity, "Ferocity")]
        [TestCase(FeatConstants.GreatCleave, "Great Cleave")]
        [TestCase(FeatConstants.GreaterSpellFocus, "Greater Spell Focus")]
        [TestCase(FeatConstants.GreaterSpellPenetration, "Greater Spell Penetration")]
        [TestCase(FeatConstants.GreaterTwoWeaponFighting, "Greater Two-Weapon Fighting")]
        [TestCase(FeatConstants.GreaterWeaponFocus, "Greater Weapon Focus")]
        [TestCase(FeatConstants.GreaterWeaponSpecialization, "Greater Weapon Specialization")]
        [TestCase(FeatConstants.GreatFortitude, "Great Fortitude")]
        [TestCase(FeatConstants.HeavyArmorProficiency, "Heavy Armor Proficiency")]
        [TestCase(FeatConstants.HeightenSpell, "Heighten Spell")]
        [TestCase(FeatConstants.HoldBreath, "Hold Breath")]
        [TestCase(FeatConstants.ImmuneToEffect, "Immune to Effect")]
        [TestCase(FeatConstants.ImprovedBullRush, "Improved Bull Rush")]
        [TestCase(FeatConstants.ImprovedCounterspell, "Improved Counterspell")]
        [TestCase(FeatConstants.ImprovedCritical, "Improved Critical")]
        [TestCase(FeatConstants.ImprovedDisarm, "Improved Disarm")]
        [TestCase(FeatConstants.ImprovedEvasion, "Improved Evasion")]
        [TestCase(FeatConstants.ImprovedFamiliar, "Improved Familiar")]
        [TestCase(FeatConstants.ImprovedFeint, "Improved Feint")]
        [TestCase(FeatConstants.ImprovedGrab, "Improved Grab")]
        [TestCase(FeatConstants.ImprovedGrapple, "Improved Grapple")]
        [TestCase(FeatConstants.ImprovedInitiative, "Improved Initiative")]
        [TestCase(FeatConstants.ImprovedOverrun, "Improved Overrun")]
        [TestCase(FeatConstants.ImprovedPreciseShot, "Improved Precise Shot")]
        [TestCase(FeatConstants.ImprovedShieldBash, "Improved Shield Bash")]
        [TestCase(FeatConstants.ImprovedSunder, "Improved Sunder")]
        [TestCase(FeatConstants.ImprovedTrip, "Improved Trip")]
        [TestCase(FeatConstants.ImprovedTurning, "Improved Turning")]
        [TestCase(FeatConstants.ImprovedTwoWeaponFighting, "Improved Two-Weapon Fighting")]
        [TestCase(FeatConstants.ImprovedUnarmedStrike, "Improved Unarmed Strike")]
        [TestCase(FeatConstants.ImprovedUncannyDodge, "Improved Uncanny Dodge")]
        [TestCase(FeatConstants.Investigator, "Investigator")]
        [TestCase(FeatConstants.IronWill, "Iron Will")]
        [TestCase(FeatConstants.Leadership, "Leadership")]
        [TestCase(FeatConstants.LightArmorProficiency, "Light Armor Proficiency")]
        [TestCase(FeatConstants.LightningReflexes, "Lightning Reflexes")]
        [TestCase(FeatConstants.LightSensitivity, "Light Sensitivity")]
        [TestCase(FeatConstants.LowLightVision, "Low-Light Vision")]
        [TestCase(FeatConstants.Lycanthropy, "Lycanthropy")]
        [TestCase(FeatConstants.Madness, "Madness")]
        [TestCase(FeatConstants.MagicalAptitude, "Magical Aptitude")]
        [TestCase(FeatConstants.MagicNaturalWeapons, "Magic Natural Weapons")]
        [TestCase(FeatConstants.Manyshot, "Manyshot")]
        [TestCase(FeatConstants.MartialWeaponProficiency, "Martial Weapon Proficiency")]
        [TestCase(FeatConstants.MaximizeSpell, "Maximize Spell")]
        [TestCase(FeatConstants.MediumArmorProficiency, "Medium Armor Proficiency")]
        [TestCase(FeatConstants.Mobility, "Mobility")]
        [TestCase(FeatConstants.MountedArchery, "Mounted Archery")]
        [TestCase(FeatConstants.MountedCombat, "Mounted Combat")]
        [TestCase(FeatConstants.NaturalArmor, "Natural Armor")]
        [TestCase(FeatConstants.NaturalSpell, "Natural Spell")]
        [TestCase(FeatConstants.NaturalWeapon, "Natural Weapon")]
        [TestCase(FeatConstants.Negotiator, "Negotiator")]
        [TestCase(FeatConstants.NimbleFingers, "Nimble Fingers")]
        [TestCase(FeatConstants.Opportunist, "Opportunist")]
        [TestCase(FeatConstants.OrcBlood, "Orc Blood")]
        [TestCase(FeatConstants.PassWithoutTrace, "Pass Without Trace")]
        [TestCase(FeatConstants.Persuasive, "Persuasive")]
        [TestCase(FeatConstants.PointBlankShot, "Point Blank Shot")]
        [TestCase(FeatConstants.PoisonUse, "Poison Use")]
        [TestCase(FeatConstants.PowerAttack, "Power Attack")]
        [TestCase(FeatConstants.PreciseShot, "Precise Shot")]
        [TestCase(FeatConstants.QuickDraw, "Quick Draw")]
        [TestCase(FeatConstants.QuickenSpell, "Quicken Spell")]
        [TestCase(FeatConstants.RapidReload, "Rapid Reload")]
        [TestCase(FeatConstants.RapidShot, "Rapid Shot")]
        [TestCase(FeatConstants.ResistanceToAcid, "Resistance to Acid")]
        [TestCase(FeatConstants.ResistanceToCold, "Resistance to Cold")]
        [TestCase(FeatConstants.ResistanceToElectricity, "Resistance to Electricity")]
        [TestCase(FeatConstants.RideByAttack, "Ride-By Attack")]
        [TestCase(FeatConstants.Run, "Run")]
        [TestCase(FeatConstants.SaveBonus, "Save Bonus")]
        [TestCase(FeatConstants.Scent, "Scent")]
        [TestCase(FeatConstants.ScribeScroll, "Scribe Scroll")]
        [TestCase(FeatConstants.SelfSufficient, "Self-Sufficient")]
        [TestCase(FeatConstants.ShieldProficiency, "Shield Proficiency")]
        [TestCase(FeatConstants.ShotOnTheRun, "Shot On The Run")]
        [TestCase(FeatConstants.SilentSpell, "Silent Spell")]
        [TestCase(FeatConstants.SimpleWeaponProficiency, "Simple Weapon Proficiency")]
        [TestCase(FeatConstants.SkillBonus, "Skill Bonus")]
        [TestCase(FeatConstants.SkillFocus, "Skill Focus")]
        [TestCase(FeatConstants.SkillMastery, "Skill Mastery")]
        [TestCase(FeatConstants.SlipperyMind, "Slippery Mind")]
        [TestCase(FeatConstants.SmiteEvil, "Smite Evil")]
        [TestCase(FeatConstants.SmiteGood, "Smite Good")]
        [TestCase(FeatConstants.SnatchArrows, "Snatch Arrows")]
        [TestCase(FeatConstants.SneakAttack, "Sneak Attack")]
        [TestCase(FeatConstants.SpellFocus, "Spell Focus")]
        [TestCase(FeatConstants.SpellLikeAbility, "Spell-Like Ability")]
        [TestCase(FeatConstants.SpellMastery, "Spell Mastery")]
        [TestCase(FeatConstants.SpellPenetration, "Spell Penetration")]
        [TestCase(FeatConstants.SpellResistance, "Spell Resistance")]
        [TestCase(FeatConstants.SpellStrength, "Spell Strength")]
        [TestCase(FeatConstants.SpiritedCharge, "Spirited Charge")]
        [TestCase(FeatConstants.SpringAttack, "Spring Attack")]
        [TestCase(FeatConstants.Stability, "Stability")]
        [TestCase(FeatConstants.Stealthy, "Stealthy")]
        [TestCase(FeatConstants.StillSpell, "Still Spell")]
        [TestCase(FeatConstants.Stonecunning, "Stonecunning")]
        [TestCase(FeatConstants.StunningFist, "Stunning Fist")]
        [TestCase(FeatConstants.Toughness, "Toughness")]
        [TestCase(FeatConstants.TowerShieldProficiency, "Tower Shield Proficiency")]
        [TestCase(FeatConstants.Track, "Track")]
        [TestCase(FeatConstants.Trample, "Trample")]
        [TestCase(FeatConstants.Trapfinding, "Trapfinding")]
        [TestCase(FeatConstants.TrapSense, "Trap Sense")]
        [TestCase(FeatConstants.Turn, "Turn")]
        [TestCase(FeatConstants.TwoWeaponFighting, "Two-Weapon Fighting")]
        [TestCase(FeatConstants.TwoWeaponDefense, "Two-Weapon Defense")]
        [TestCase(FeatConstants.UncannyDodge, "Uncanny Dodge")]
        [TestCase(FeatConstants.VulnerabilityToSunlight, "Vulnerability to Sunlight")]
        [TestCase(FeatConstants.WeaponFamiliarity, "Weapon Familiarity")]
        [TestCase(FeatConstants.WeaponFinesse, "Weapon Finesse")]
        [TestCase(FeatConstants.WeaponFocus, "Weapon Focus")]
        [TestCase(FeatConstants.WeaponProficiency, "Weapon Proficiency")]
        [TestCase(FeatConstants.WeaponSpecialization, "Weapon Specialization")]
        [TestCase(FeatConstants.WidenSpell, "Widen Spell")]
        [TestCase(FeatConstants.WhirlwindAttack, "Whirlwind Attack")]
        [TestCase(FeatConstants.FastMovement, "Fast Movement")]
        [TestCase(FeatConstants.Illiteracy, "Illiteracy")]
        [TestCase(FeatConstants.Rage, "Rage")]
        [TestCase(FeatConstants.GreaterRage, "Greater Rage")]
        [TestCase(FeatConstants.IndomitableWill, "Indomitable Will")]
        [TestCase(FeatConstants.TirelessRage, "Tireless Rage")]
        [TestCase(FeatConstants.MightyRage, "Mighty Rage")]
        [TestCase(FeatConstants.BardicMusic, "Bardic Music")]
        [TestCase(FeatConstants.BardicKnowledge, "Bardic Knowledge")]
        [TestCase(FeatConstants.Countersong, "Countersong")]
        [TestCase(FeatConstants.Fascinate, "Fascinate")]
        [TestCase(FeatConstants.InspireCourage, "Inspire Courage")]
        [TestCase(FeatConstants.Suggestion, "Suggestion")]
        [TestCase(FeatConstants.InspireGreatness, "Inspire Greatness")]
        [TestCase(FeatConstants.SongOfFreedom, "Song of Freedom")]
        [TestCase(FeatConstants.InspireHeroics, "Inspire Heroics")]
        [TestCase(FeatConstants.MassSuggestion, "Mass Suggestion")]
        [TestCase(FeatConstants.InspireCompetence, "Inspire Competence")]
        [TestCase(FeatConstants.FavoredEnemy, "Favored Enemy")]
        [TestCase(FeatConstants.WildEmpathy, "Wild Empathy")]
        [TestCase(FeatConstants.CombatStyle, "Combat Style")]
        [TestCase(FeatConstants.ImprovedCombatStyle, "Improved Combat Style")]
        [TestCase(FeatConstants.WoodlandStride, "Woodland Stride")]
        [TestCase(FeatConstants.SwiftTracker, "Swift Tracker")]
        [TestCase(FeatConstants.CombatStyleMastery, "Combat Style Mastery")]
        [TestCase(FeatConstants.Camouflage, "Camouflage")]
        [TestCase(FeatConstants.HideInPlainSight, "Hide in Plain Sight")]
        [TestCase(FeatConstants.CastSpellBonus, "Cast Spell Bonus")]
        [TestCase(FeatConstants.DeathTouch, "Death Touch")]
        [TestCase(FeatConstants.PassiveSecretDoorSearch, "Passive Secret Door Search")]
        [TestCase(FeatConstants.ImprovedSpell, "Improved Spell")]
        [TestCase(FeatConstants.SupernaturalStrength, "Supernatural Strength")]
        public void ConstantName(String constant, String value)
        {
            Assert.That(constant, Is.EqualTo(value));
        }

        [TestCase(FeatConstants.AcrobaticId, "Acrobatic")]
        [TestCase(FeatConstants.AgileId, "Agile")]
        [TestCase(FeatConstants.AlertnessId, "Alertness")]
        [TestCase(FeatConstants.AlternateFormId, "AlternateForm")]
        [TestCase(FeatConstants.AnimalAffinityId, "AnimalAffinity")]
        [TestCase(FeatConstants.AthleticId, "Athletic")]
        [TestCase(FeatConstants.AttackBonusId, "AttackBonus")]
        [TestCase(FeatConstants.AugmentSummoningId, "AugmentSummoning")]
        [TestCase(FeatConstants.BlindFightId, "BlindFight")]
        [TestCase(FeatConstants.ChangeShapeId, "ChangeShape")]
        [TestCase(FeatConstants.CleaveId, "Cleave")]
        [TestCase(FeatConstants.CombatCastingId, "CombatCasting")]
        [TestCase(FeatConstants.CombatExpertiseId, "CombatExpertise")]
        [TestCase(FeatConstants.CombatReflexesId, "CombatReflexes")]
        [TestCase(FeatConstants.CripplingStrikeId, "CripplingStrike")]
        [TestCase(FeatConstants.DamageReductionId, "DamageReduction")]
        [TestCase(FeatConstants.DarkvisionId, "Darkvision")]
        [TestCase(FeatConstants.DeceitfulId, "Deceitful")]
        [TestCase(FeatConstants.DefensiveRollId, "DefensiveRoll")]
        [TestCase(FeatConstants.DeflectArrowsId, "DeflectArrows")]
        [TestCase(FeatConstants.DeftHandsId, "DeftHands")]
        [TestCase(FeatConstants.DiehardId, "Diehard")]
        [TestCase(FeatConstants.DiligentId, "Diligent")]
        [TestCase(FeatConstants.DodgeId, "Dodge")]
        [TestCase(FeatConstants.DodgeBonusId, "DodgeBonus")]
        [TestCase(FeatConstants.ElvenBloodId, "ElvenBlood")]
        [TestCase(FeatConstants.EmpathyId, "Empathy")]
        [TestCase(FeatConstants.EmpowerSpellId, "EmpowerSpell")]
        [TestCase(FeatConstants.EnduranceId, "Endurance")]
        [TestCase(FeatConstants.EnlargeSpellId, "EnlargeSpell")]
        [TestCase(FeatConstants.EschewMaterialsId, "EschewMaterials")]
        [TestCase(FeatConstants.EvasionId, "Evasion")]
        [TestCase(FeatConstants.ExoticWeaponProficiencyId, "ExoticWeaponProficiency")]
        [TestCase(FeatConstants.ExtendSpellId, "ExtendSpell")]
        [TestCase(FeatConstants.ExtraTurningId, "ExtraTurning")]
        [TestCase(FeatConstants.FarShotId, "FarShot")]
        [TestCase(FeatConstants.FerocityId, "Ferocity")]
        [TestCase(FeatConstants.GreatCleaveId, "GreatCleave")]
        [TestCase(FeatConstants.GreaterSpellFocusId, "GreaterSpellFocus")]
        [TestCase(FeatConstants.GreaterSpellPenetrationId, "GreaterSpellPenetration")]
        [TestCase(FeatConstants.GreaterTwoWeaponFightingId, "GreaterTwoWeaponFighting")]
        [TestCase(FeatConstants.GreaterWeaponFocusId, "GreaterWeaponFocus")]
        [TestCase(FeatConstants.GreaterWeaponSpecializationId, "GreaterWeaponSpecialization")]
        [TestCase(FeatConstants.GreatFortitudeId, "GreatFortitude")]
        [TestCase(FeatConstants.HeavyArmorProficiencyId, "HeavyArmorProficiency")]
        [TestCase(FeatConstants.HeightenSpellId, "HeightenSpell")]
        [TestCase(FeatConstants.HoldBreathId, "HoldBreath")]
        [TestCase(FeatConstants.ImmuneToEffectId, "ImmuneToEffect")]
        [TestCase(FeatConstants.ImprovedBullRushId, "ImprovedBullRush")]
        [TestCase(FeatConstants.ImprovedCounterspellId, "ImprovedCounterspell")]
        [TestCase(FeatConstants.ImprovedCriticalId, "ImprovedCritical")]
        [TestCase(FeatConstants.ImprovedDisarmId, "ImprovedDisarm")]
        [TestCase(FeatConstants.ImprovedEvasionId, "ImprovedEvasion")]
        [TestCase(FeatConstants.ImprovedFamiliarId, "ImprovedFamiliar")]
        [TestCase(FeatConstants.ImprovedFeintId, "ImprovedFeint")]
        [TestCase(FeatConstants.ImprovedGrabId, "ImprovedGrab")]
        [TestCase(FeatConstants.ImprovedGrappleId, "ImprovedGrapple")]
        [TestCase(FeatConstants.ImprovedInitiativeId, "ImprovedInitiative")]
        [TestCase(FeatConstants.ImprovedOverrunId, "ImprovedOverrun")]
        [TestCase(FeatConstants.ImprovedPreciseShotId, "ImprovedPreciseShot")]
        [TestCase(FeatConstants.ImprovedShieldBashId, "ImprovedShieldBash")]
        [TestCase(FeatConstants.ImprovedSunderId, "ImprovedSunder")]
        [TestCase(FeatConstants.ImprovedTripId, "ImprovedTrip")]
        [TestCase(FeatConstants.ImprovedTurningId, "ImprovedTurning")]
        [TestCase(FeatConstants.ImprovedTwoWeaponFightingId, "ImprovedTwoWeaponFighting")]
        [TestCase(FeatConstants.ImprovedUnarmedStrikeId, "ImprovedUnarmedStrike")]
        [TestCase(FeatConstants.ImprovedUncannyDodgeId, "ImprovedUncannyDodge")]
        [TestCase(FeatConstants.InvestigatorId, "Investigator")]
        [TestCase(FeatConstants.IronWillId, "IronWill")]
        [TestCase(FeatConstants.LeadershipId, "Leadership")]
        [TestCase(FeatConstants.LightArmorProficiencyId, "LightArmorProficiency")]
        [TestCase(FeatConstants.LightningReflexesId, "LightningReflexes")]
        [TestCase(FeatConstants.LightSensitivityId, "LightSensitivity")]
        [TestCase(FeatConstants.LowLightVisionId, "LowLightVision")]
        [TestCase(FeatConstants.LycanthropyId, "Lycanthropy")]
        [TestCase(FeatConstants.MadnessId, "Madness")]
        [TestCase(FeatConstants.MagicalAptitudeId, "MagicalAptitude")]
        [TestCase(FeatConstants.MagicNaturalWeaponsId, "MagicNaturalWeapons")]
        [TestCase(FeatConstants.ManyshotId, "Manyshot")]
        [TestCase(FeatConstants.MartialWeaponProficiencyId, "MartialWeaponProficiency")]
        [TestCase(FeatConstants.MaximizeSpellId, "MaximizeSpell")]
        [TestCase(FeatConstants.MediumArmorProficiencyId, "MediumArmorProficiency")]
        [TestCase(FeatConstants.MobilityId, "Mobility")]
        [TestCase(FeatConstants.MountedArcheryId, "MountedArchery")]
        [TestCase(FeatConstants.MountedCombatId, "MountedCombat")]
        [TestCase(FeatConstants.NaturalArmorId, "NaturalArmor")]
        [TestCase(FeatConstants.NaturalSpellId, "NaturalSpell")]
        [TestCase(FeatConstants.NaturalWeaponId, "NaturalWeapon")]
        [TestCase(FeatConstants.NegotiatorId, "Negotiator")]
        [TestCase(FeatConstants.NimbleFingersId, "NimbleFingers")]
        [TestCase(FeatConstants.OpportunistId, "Opportunist")]
        [TestCase(FeatConstants.OrcBloodId, "OrcBlood")]
        [TestCase(FeatConstants.PassWithoutTraceId, "PassWithoutTrace")]
        [TestCase(FeatConstants.PersuasiveId, "Persuasive")]
        [TestCase(FeatConstants.PointBlankShotId, "PointBlankShot")]
        [TestCase(FeatConstants.PoisonUseId, "PoisonUse")]
        [TestCase(FeatConstants.PowerAttackId, "PowerAttack")]
        [TestCase(FeatConstants.PreciseShotId, "PreciseShot")]
        [TestCase(FeatConstants.QuickDrawId, "QuickDraw")]
        [TestCase(FeatConstants.QuickenSpellId, "QuickenSpell")]
        [TestCase(FeatConstants.RapidReloadId, "RapidReload")]
        [TestCase(FeatConstants.RapidShotId, "RapidShot")]
        [TestCase(FeatConstants.ResistanceToAcidId, "ResistanceToAcid")]
        [TestCase(FeatConstants.ResistanceToColdId, "ResistanceToCold")]
        [TestCase(FeatConstants.ResistanceToElectricityId, "ResistanceToElectricity")]
        [TestCase(FeatConstants.RideByAttackId, "RideByAttack")]
        [TestCase(FeatConstants.RunId, "Run")]
        [TestCase(FeatConstants.SaveBonusId, "SaveBonus")]
        [TestCase(FeatConstants.ScentId, "Scent")]
        [TestCase(FeatConstants.ScribeScrollId, "ScribeScroll")]
        [TestCase(FeatConstants.SelfSufficientId, "SelfSufficient")]
        [TestCase(FeatConstants.ShieldProficiencyId, "ShieldProficiency")]
        [TestCase(FeatConstants.ShotOnTheRunId, "ShotOnTheRun")]
        [TestCase(FeatConstants.SilentSpellId, "SilentSpell")]
        [TestCase(FeatConstants.SimpleWeaponProficiencyId, "SimpleWeaponProficiency")]
        [TestCase(FeatConstants.SkillBonusId, "SkillBonus")]
        [TestCase(FeatConstants.SkillFocusId, "SkillFocus")]
        [TestCase(FeatConstants.SkillMasteryId, "SkillMastery")]
        [TestCase(FeatConstants.SlipperyMindId, "SlipperyMind")]
        [TestCase(FeatConstants.SmiteEvilId, "SmiteEvil")]
        [TestCase(FeatConstants.SmiteGoodId, "SmiteGood")]
        [TestCase(FeatConstants.SnatchArrowsId, "SnatchArrows")]
        [TestCase(FeatConstants.SneakAttackId, "SneakAttack")]
        [TestCase(FeatConstants.SpellFocusId, "SpellFocus")]
        [TestCase(FeatConstants.SpellLikeAbilityId, "SpellLikeAbility")]
        [TestCase(FeatConstants.SpellMasteryId, "SpellMastery")]
        [TestCase(FeatConstants.SpellPenetrationId, "SpellPenetration")]
        [TestCase(FeatConstants.SpellResistanceId, "SpellResistance")]
        [TestCase(FeatConstants.SpellStrengthId, "SpellStrength")]
        [TestCase(FeatConstants.SpiritedChargeId, "SpiritedCharge")]
        [TestCase(FeatConstants.SpringAttackId, "SpringAttack")]
        [TestCase(FeatConstants.StabilityId, "Stability")]
        [TestCase(FeatConstants.StillSpellId, "StillSpell")]
        [TestCase(FeatConstants.StonecunningId, "Stonecunning")]
        [TestCase(FeatConstants.StunningFistId, "StunningFist")]
        [TestCase(FeatConstants.ToughnessId, "Toughness")]
        [TestCase(FeatConstants.TowerShieldProficiencyId, "TowerShieldProficiency")]
        [TestCase(FeatConstants.TrackId, "Track")]
        [TestCase(FeatConstants.TrampleId, "Trample")]
        [TestCase(FeatConstants.TrapfindingId, "Trapfinding")]
        [TestCase(FeatConstants.TrapSenseId, "TrapSense")]
        [TestCase(FeatConstants.TurnId, "Turn")]
        [TestCase(FeatConstants.TwoWeaponFightingId, "TwoWeaponFighting")]
        [TestCase(FeatConstants.TwoWeaponDefenseId, "TwoWeaponDefense")]
        [TestCase(FeatConstants.UncannyDodgeId, "UncannyDodge")]
        [TestCase(FeatConstants.VulnerabilityToSunlightId, "VulnerabilityToSunlight")]
        [TestCase(FeatConstants.WeaponFamiliarityId, "WeaponFamiliarity")]
        [TestCase(FeatConstants.WeaponFinesseId, "WeaponFinesse")]
        [TestCase(FeatConstants.WeaponFocusId, "WeaponFocus")]
        [TestCase(FeatConstants.WeaponProficiencyId, "WeaponProficiency")]
        [TestCase(FeatConstants.WeaponSpecializationId, "WeaponSpecialization")]
        [TestCase(FeatConstants.WidenSpellId, "WidenSpell")]
        [TestCase(FeatConstants.WhirlwindAttackId, "WhirlwindAttack")]
        [TestCase(FeatConstants.FastMovementId, "FastMovement")]
        [TestCase(FeatConstants.IlliteracyId, "Illiteracy")]
        [TestCase(FeatConstants.RageId, "Rage")]
        [TestCase(FeatConstants.GreaterRageId, "GreaterRage")]
        [TestCase(FeatConstants.IndomitableWillId, "IndomitableWill")]
        [TestCase(FeatConstants.TirelessRageId, "TirelessRage")]
        [TestCase(FeatConstants.MightyRageId, "MightyRage")]
        [TestCase(FeatConstants.BardicMusicId, "BardicMusic")]
        [TestCase(FeatConstants.BardicKnowledgeId, "BardicKnowledge")]
        [TestCase(FeatConstants.CountersongId, "Countersong")]
        [TestCase(FeatConstants.FascinateId, "Fascinate")]
        [TestCase(FeatConstants.InspireCourageId, "InspireCourage")]
        [TestCase(FeatConstants.SuggestionId, "Suggestion")]
        [TestCase(FeatConstants.InspireGreatnessId, "InspireGreatness")]
        [TestCase(FeatConstants.SongOfFreedomId, "SongOfFreedom")]
        [TestCase(FeatConstants.InspireHeroicsId, "InspireHeroics")]
        [TestCase(FeatConstants.MassSuggestionId, "MassSuggestion")]
        [TestCase(FeatConstants.InspireCompetenceId, "InspireCompetence")]
        [TestCase(FeatConstants.FavoredEnemyId, "FavoredEnemy")]
        [TestCase(FeatConstants.WildEmpathyId, "WildEmpathy")]
        [TestCase(FeatConstants.CombatStyleId, "CombatStyle")]
        [TestCase(FeatConstants.ImprovedCombatStyleId, "ImprovedCombatStyle")]
        [TestCase(FeatConstants.WoodlandStrideId, "WoodlandStride")]
        [TestCase(FeatConstants.SwiftTrackerId, "SwiftTracker")]
        [TestCase(FeatConstants.CombatStyleMasteryId, "CombatStyleMastery")]
        [TestCase(FeatConstants.CamouflageId, "Camouflage")]
        [TestCase(FeatConstants.HideInPlainSightId, "HideInPlainSight")]
        [TestCase(FeatConstants.CastSpellBonusId, "CastSpellBonus")]
        [TestCase(FeatConstants.DeathTouchId, "DeathTouch")]
        [TestCase(FeatConstants.PassiveSecretDoorSearchId, "PassiveSecretDoorSearch")]
        [TestCase(FeatConstants.ImprovedSpellId, "ImprovedSpell")]
        [TestCase(FeatConstants.SupernaturalStrengthId, "SupernaturalStrength")]
        public void ConstantId(String constant, String value)
        {
            Assert.That(constant, Is.EqualTo(value));
        }

        [TestCase(FeatConstants.Frequencies.Constant, "Constant")]
        [TestCase(FeatConstants.Frequencies.AtWill, "At Will")]
        [TestCase(FeatConstants.Frequencies.Day, "Day")]
        [TestCase(FeatConstants.Frequencies.Round, "Round")]
        [TestCase(FeatConstants.Foci.Archery, "Archery")]
        public void Constant(String constant, String value)
        {
            Assert.That(constant, Is.EqualTo(value));
        }
    }
}