using System;

namespace CharacterGen.Common.Magics
{
    public static class SpellConstants
    {
        public const String Aid = "Aid";
        public const String Blasphemy = "Blasphemy";
        public const String Bless = "Bless";
        public const String BlindnessDeafness = "Blindness/deafness";
        public const String Blur = "Blur";
        public const String CharmMonster = "Charm monster";
        public const String CharmPerson = "Charm person";
        public const String ConeOfCold = "Cone of cold";
        public const String Contagion = "Contagion";
        public const String CureCriticalWounds = "Cure critical wounds";
        public const String CureLightWounds = "Cure light wounds";
        public const String CureModerateWounds = "Cure moderate wounds";
        public const String CureSeriousWounds = "Cure serious wounds";
        public const String DancingLights = "Dancing lights";
        public const String Darkness = "Darkness";
        public const String Daylight = "Daylight";
        public const String Daze = "Daze";
        public const String Desecrate = "Desecrate";
        public const String Destruction = "Destruction";
        public const String DetectEvil = "Detect evil";
        public const String DetectThoughts = "Detect thoughts";
        public const String DisguiseSelf = "Disguise self";
        public const String DispelEvil = "Dispel evil";
        public const String EnlargePerson = "Enlarge person";
        public const String FaerieFire = "Faerie fire";
        public const String FreedomOfMovement = "Freedom of movement";
        public const String GaseousForm = "Gaseous form";
        public const String GhostSound = "Ghost sound";
        public const String Hallow = "Hallow";
        public const String Heal = "Heal";
        public const String HolyAura = "Holy aura";
        public const String HolySmite = "Holy smite";
        public const String HolyWord = "Holy word";
        public const String HorridWilting = "Horrid wilting";
        public const String Invisibility = "Invisibility";
        public const String Levitate = "Levitate";
        public const String MassCharmMonster = "Mass charm monster";
        public const String NeutralizePoison = "Neutralize poison";
        public const String Nondetection = "Nondetection";
        public const String PassWithoutTrace = "Pass without trace";
        public const String PlaneShift = "Plane shift";
        public const String Poison = "Poison";
        public const String Polymorph = "Polymorph";
        public const String Prestidigitation = "Prestidigitation";
        public const String ProtectionFromEvil = "Protection from evil";
        public const String RemoveDisease = "Remove disease";
        public const String Resurrection = "Resurrection";
        public const String Sleep = "Sleep";
        public const String SoundBurst = "Sound burst";
        public const String SpeakWithAnimals = "Speak with animals";
        public const String SpiderClimb = "Spider climb";
        public const String Suggestion = "Suggestion";
        public const String SummonMonsterI = "Summon monster I";
        public const String SummonMonsterII = "Summon monster II";
        public const String SummonMonsterIII = "Summon monster III";
        public const String SummonMonsterIV = "Summon monster IV";
        public const String SummonMonsterV = "Summon monster V";
        public const String SummonMonsterVI = "Summon monster VI";
        public const String SummonMonsterVII = "Summon monster VII";
        public const String SummonMonsterVIII = "Summon monster VIII";
        public const String SummonMonsterIX = "Summon monster IX";
        public const String SummonNaturesAllyI = "Summon nature's ally I";
        public const String SummonNaturesAllyII = "Summon nature's ally II";
        public const String SummonNaturesAllyIII = "Summon nature's ally III";
        public const String SummonNaturesAllyIV = "Summon nature's ally IV";
        public const String SummonNaturesAllyV = "Summon nature's ally V";
        public const String SummonNaturesAllyVI = "Summon nature's ally VI";
        public const String SummonNaturesAllyVII = "Summon nature's ally VII";
        public const String SummonNaturesAllyVIII = "Summon nature's ally VIII";
        public const String SummonNaturesAllyIX = "Summon nature's ally IX";
        public const String Unhallow = "Unhallow";
        public const String UnholyAura = "Unholy aura";
        public const String UnholyBlight = "Unholy blight";
    }
}